Arena/Arena.Web/ViewModels/Rezervacije/RezervacijaDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.ViewModels.Rezervacije
{
    public class RezervacijaDodajVM
    {
        [Required(ErrorMessage = "Molimo odaberite termin.")]
        public int? OdabraniTerminId { get; set; }
        public List<SelectListItem> Termini { get; set; }

        [Required(ErrorMessage = "Molimo odaberite klijenta.")]
        public int? OdabraniKlijentId{ get; set; }
        public List<SelectListItem> Klijenti{ get; set; }
    }
}

Arena/Arena.Web/ViewModels/Rezervacije/RezervacijaEditVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.ViewModels.Rezervacije
{
    public class RezervacijaEditVM
    {
        public int ID { get; set; }


        [Required(ErrorMessage = "Molimo odaberite termin.")]
        public int? OdabraniTerminId { get; set; }
        public List<SelectListItem> Termini { get; set; }

        [Required(ErrorMessage = "Molimo odaberite klijenta.")]
        public int? OdabraniKlijentId { get; set; }
        public List<SelectListItem> Klijenti { get; set; }


        public bool OdobrenaRezervacija { get; set; }
    }
}

Arena/Arena.Web/ViewModels/Rezervacije/RezervacijeIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.ViewModels.Rezervacije
{
    public class RezervacijeIndexVM
    {
        public int ID { get; set; }
        public int TerminID { get; set; }

        public DateTime DatumIVrijemeTermina { get; set; }
        public string NazivDvorane { get; set; }
        public bool Placeno { get; set; }

        public string Ime { get; set; }
        public string Prezime { get; set; }

        public bool OdobrenaRezervacija { get; set; }
    }
}

Arena/Arena.Web/ViewModels/Rezervacije/RezervacijePretragaVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.ViewModels.Rezervacije
{
    public class RezervacijePretragaVM
    {

        [Display(Name = "Dvorana")]
        public int? OdabranaDvorana { get; set; }
        public List<SelectListItem> Dvorane { get; set; }
        [Display(Name = "Ime klijenta", Prompt ="Upišite ime klijenta")]
        public string ImeKlijenta { get; set; }
        [Display(Name="Prezime klijenta",Prompt ="Upišite prezime klijenta")]
        public string PrezimeKlijenta { get; set; }


        public List<RezervacijeIndexVM> RezultatPretrage { get; set; }
    }
}

Arena/Arena.Web/Controllers/RezervacijeController.cs
using Arena.EF;
using Arena.Models;
using Arena.Web.ViewModels.Rezervacije;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.Controllers
{
    public class RezervacijeController : Controller
    {
        private MojDbContext context;

        public RezervacijeController(MojDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new RezervacijePretragaVM();
            model.Dvorane = GetDvorane();


            model.RezultatPretrage = context.Rezervacije
            .OrderByDescending(x => x.Termin.DatumIVrijeme)
            .Select(x => new RezervacijeIndexVM()
            {
                ID = x.ID,
                TerminID = x.TerminID,
                DatumIVrijemeTermina = x.Termin.DatumIVrijeme,
                Ime = x.Klijent.Ime,
                Prezime = x.Klijent.Prezime,
                NazivDvorane = x.Termin.Dvorana.Naziv,
                OdobrenaRezervacija = x.OdobrenaRezervacija,
                Placeno = x.UplataID != null
            })
            .ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Pretraga(RezervacijePretragaVM model)
        {
            model.Dvorane = GetDvorane();

            var imeLowercase = model.ImeKlijenta?.ToLower();
            var prezimeLowercase = model.PrezimeKlijenta?.ToLower();

            model.RezultatPretrage = context.Rezervacije
            .OrderByDescending(x => x.Termin.DatumIVrijeme)
            .Where(x => model.OdabranaDvorana == null || x.Termin.DvoranaID == model.OdabranaDvorana)
            .Where(x => string.IsNullOrEmpty(imeLowercase) || x.Klijent.Ime.ToLower().Contains(imeLowercase))
            .Where(x => string.IsNullOrEmpty(prezimeLowercase) || x.Klijent.Prezime.ToLower().Contains(prezimeLowercase))
            .Select(x => new RezervacijeIndexVM()
            {
                ID = x.ID,
                TerminID = x.TerminID,
                DatumIVrijemeTermina = x.Termin.DatumIVrijeme,
                Ime = x.Klijent.Ime,
                Prezime = x.Klijent.Prezime,
                NazivDvorane = x.Termin.Dvorana.Naziv,
                OdobrenaRezervacija = x.OdobrenaRezervacija,
                Placeno = x.UplataID != null
            })
            .ToList();
            return View("Index", model);

        }


        [HttpGet]
        public IActionResult Dodaj()
        {
            var model = new RezervacijaDodajVM();
            model.Termini = GetTermini();
            model.Klijenti = GetKlijenti();
            return View("Dodaj", model);
        }

        [HttpPost]
        public IActionResult Dodaj(RezervacijaDodajVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Termini = GetTermini();
                model.Klijenti = GetKlijenti();
                return View("Dodaj", model);
            }

            var novaRezervacija = new Rezervacija
            {
                KlijentID = model.OdabraniKlijentId.Value,
                OdobrenaRezervacija=false,
                TerminID= model.OdabraniTerminId.Value,
                UplataID= null
            };

            context.Rezervacije.Add(novaRezervacija);
            context.SaveChanges();

            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            var rezervacija = context.Rezervacije.FirstOrDefault(x => x.ID == id);

            var model = new RezervacijaEditVM();
            model.Termini = GetTermini();
            model.Klijenti = GetKlijenti();

            model.ID = rezervacija.ID;
            model.OdabraniKlijentId = rezervacija.KlijentID;
            model.OdabraniTerminId = rezervacija.TerminID;
            model.OdobrenaRezervacija = rezervacija.OdobrenaRezervacija;

            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Edit(int id, RezervacijaEditVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Termini = GetTermini();
                model.Klijenti = GetKlijenti();
                return View("Edit", model);
            }
            var rezervacija = context.Rezervacije.FirstOrDefault(x => x.ID == id);

            rezervacija.KlijentID = model.OdabraniKlijentId.Value;
            rezervacija.TerminID = model.OdabraniTerminId.Value;
            rezervacija.OdobrenaRezervacija = model.OdobrenaRezervacija;

            context.Rezervacije.Update(rezervacija);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        private List<SelectListItem> GetKlijenti()
        {
            var dostupniKlijenti = context.Klijenti
                        .Select(x => new SelectListItem
                        {
                            Text = x.Ime + " " + x.Prezime + " " + x.JBMG,
                            Value = x.ID.ToString()
                        }).ToList();


            dostupniKlijenti.Insert(0, new SelectListItem
            {
                Text = "--Odaberite klijenta--",
                Value = null
            });
            return dostupniKlijenti;
        }

        private List<SelectListItem> GetTermini()
        {
            var dostupniTermini = context.Termini
                .Select(x => new SelectListItem
                {
                    Text = x.DatumIVrijeme.ToString("dd.MM.yyyy HH:mm") + " - " + x.Dvorana.Naziv,
                    Value = x.ID.ToString()
                }).ToList();


            dostupniTermini.Insert(0, new SelectListItem
            {
                Text = "--Odaberite termin--",
                Value = null
            });
            return dostupniTermini;
        }

        private List<SelectListItem> GetDvorane()
        {
            var dostupneDvorane = context.Dvorana.Select(x => new SelectListItem
            {
                Text = x.Naziv,
                Value = x.ID.ToString()
            }).ToList();
            dostupneDvorane.Insert(0, new SelectListItem
            {
                Text = "--Odaberite dvoranu--",
                Value = null
            });
            return dostupneDvorane;
        }
    }
}

Arena/Arena.Web/Views/Rezervacije/Dodaj.cshtml
@model Arena.Web.ViewModels.Rezervacije.RezervacijaDodajVM
@{
    ViewData["Title"] = "Dodaj rezervaciju";
}


<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">

                <form asp-action="Dodaj" method="post" autocomplete="off">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label asp-for="@Model.OdabraniTerminId"></label>
                            <select asp-for="@Model.OdabraniTerminId" asp-items="@Model.Termini" class="form-control"></select>
                            <span class="text-danger" asp-validation-for="@Model.OdabraniTerminId"></span>
                        </div>


                        <div class="form-group col-md-12">
                            <label asp-for="@Model.OdabraniKlijentId"></label>
                            <select asp-for="@Model.OdabraniKlijentId" asp-items="@Model.Klijenti" class="form-control"></select>
                            <span class="text-danger" asp-validation-for="@Model.OdabraniKlijentId"></span>
                        </div>

                       
                        <div class="form-group col-md-12">
                            <a class="btn btn-default " asp-controller="Rezervacije" asp-action="Index">Nazad</a>
                            <button type="submit" class="btn btn-primary ">Spremi</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>

</div>

Arena/Arena.Web/Views/Rezervacije/Edit.cshtml
@model Arena.Web.ViewModels.Rezervacije.RezervacijaEditVM
@{
    ViewData["Title"] = "Ažuriraj rezervaciju";
}


<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">


                <form asp-action="Edit" method="post" autocomplete="off">
                    <input asp-for="@Model.ID" type="hidden" />
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label asp-for="@Model.OdabraniTerminId"></label>
                            <select asp-for="@Model.OdabraniTerminId" asp-items="@Model.Termini" class="form-control"></select>
                            <span class="text-danger" asp-validation-for="@Model.OdabraniTerminId"></span>
                        </div>


                        <div class="form-group col-md-12">
                            <label asp-for="@Model.OdabraniKlijentId"></label>
                            <select asp-for="@Model.OdabraniKlijentId" asp-items="@Model.Klijenti" class="form-control"></select>
                            <span class="text-danger" asp-validation-for="@Model.OdabraniKlijentId"></span>
                        </div>


                        <div class="form-group col-md-12">
                            <div class="icheck-primary">
                                <input asp-for="@Model.OdobrenaRezervacija" type="checkbox">
                                <label asp-for="@Model.OdobrenaRezervacija"></label>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <a class="btn btn-default " asp-controller="Rezervacije" asp-action="Index">Nazad</a>
                            <button type="submit" class="btn btn-primary ">Spremi</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>

</div>

Arena/Arena.Web/Views/Rezervacije/Index.cshtml
@model Arena.Web.ViewModels.Rezervacije.RezervacijePretragaVM
@{
    ViewData["Title"] = "Rezervacije";
}


<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form asp-action="Pretraga" method="post" autocomplete="off">
                    <div class="row">

                        <div class="form-group col-md-4">
                            <label asp-for="@Model.OdabranaDvorana"></label>
                            <select asp-for="@Model.OdabranaDvorana"
                                    asp-items="@Model.Dvorane"
                                    class="form-control">
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="@Model.ImeKlijenta"></label>
                            <input asp-for="@Model.ImeKlijenta" class="form-control" />
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="@Model.PrezimeKlijenta"></label>
                            <input asp-for="@Model.PrezimeKlijenta" class="form-control" />
                        </div>
                        <div class="form-group col-md-4">
                            <button type="submit" class="btn btn-primary ">Pretraga</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Rezervacije</h3>
                <a asp-controller="Rezervacije" asp-action="Dodaj" class="btn btn-outline-primary float-right">Dodaj</a>

            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped">


                    @*public int ID { get; set; }
                    public int TerminID { get; set; }

                    public DateTime DatumIVrijemeTermina { get; set; }
                    public string NazivDvorane { get; set; }
                    public bool Placeno { get; set; }

                    public string Ime { get; set; }
                    public string Prezime { get; set; }

                    public bool OdobrenaRezervacija { get; set; }*@
                    <thead>
                        <tr>
                            <th style="width: 10px">#ID</th>
                            <th>Datum termina</th>
                            <th>Dvorana</th>
                            <th>Placeno</th>
                            <th>Ime i prezime klijenta</th>
                            <th>Je odobrena?</th>
                            <th>Akcije</th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in Model.RezultatPretrage)
                        {
                            <tr>
                                <td>@item.ID</td>
                                <td>@item.DatumIVrijemeTermina.ToString("dd.MM.yyyy HH:mm")</td>
                                <td>@item.NazivDvorane</td>
                                <td>@item.Placeno</td>
                                <td>@item.Ime  @item.Prezime</td>
                                <td>@item.OdobrenaRezervacija</td>
                                <td>
                                    <a asp-controller="Rezervacije" asp-action="Edit" asp-route-id="@item.ID">
                                        <i class="fas fa-edit"></i> Izmjeni
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>

    </div>

</div>