Arena/Arena.Web/Controllers/AutentifikacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Arena.EF;
using Arena.Models;
using Arena.Web.Helper;
using Arena.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Arena.Web.Controllers
{
    public class AutentifikacijaController : Controller
    {
        private MojDbContext db;
        private readonly SignInManager<Nalog> signInManager;
        private readonly UserManager<Nalog> userManager;
        private IHttpContextAccessor httpContext;

        public AutentifikacijaController(MojDbContext db, IHttpContextAccessor httpContext, SignInManager<Nalog> signInManager, UserManager<Nalog> userManager)
        {
            this.db = db;
            this.httpContext = httpContext;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public IActionResult Prijava()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public async Task<IActionResult> Prijava(LoginVM login)
        {

            if (!ModelState.IsValid)
            {
                return View(login);
            }

            //pronadjemo korisnika iz baze po korisnickom imenu
            var user = await userManager.FindByNameAsync(login.Username);
            if (user == null)
            {
                ModelState.AddModelError("","Neispravna lozinka ili kor. ime.");
                return View(login);
            }

            var signInResult = await signInManager.CheckPasswordSignInAsync(user, login.Password, false);
            if (!signInResult.Succeeded)
            {
                ModelState.AddModelError("", "Neispravna lozinka ili kor. ime.");
                return View(login);
            }

            await signInManager.SignInAsync(user, login.ZapamtiPassword);
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Odjava()
        {
            await signInManager.SignOutAsync();
            //Autentifikacija.OcistiSesiju(httpContext.HttpContext);
            return RedirectToAction("Prijava");
        }
    }
}

Arena/Arena.Web/Controllers/KlijentiController.cs
using Arena.EF;
using Arena.Models;
using Arena.Web.ViewModels.Klijenti;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.Controllers
{
    public class KlijentiController :Controller
    {

        private MojDbContext context;
        private UserManager<Nalog> userManager;
        private SignInManager<Nalog> signInManager;
        public KlijentiController(MojDbContext context, UserManager<Nalog> userManager, SignInManager<Nalog> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Registriraj()
        {

            var model = new KlijentRegistrirajVM();
           
            model.Gradovi = GetGradoviDropdown();
            return View("Registriraj", model);
        }

        [HttpPost]
        public async Task<IActionResult> Registriraj(KlijentRegistrirajVM model)
        {

            if(!ModelState.IsValid)
            {
                model.Gradovi = GetGradoviDropdown();
                return View("Registriraj", model);
            }


            var pwValidaton = new PasswordValidator<Nalog>();
            var validationResult =  await pwValidaton
                .ValidateAsync(userManager, null, model.Password);
            if (!validationResult.Succeeded)
            {

                foreach (var item in validationResult.Errors.Select(x=>x.Description))
                {
                    ModelState.AddModelError("", item);
                }
                model.Gradovi = GetGradoviDropdown();
                return View("Registriraj", model);

            }


            var postojeciKorisnik = await userManager.FindByNameAsync(model.Username);
            if (postojeciKorisnik != null)
            {
                ModelState.AddModelError("", "Korisnicko ime je zauzeto.");
                model.Gradovi = GetGradoviDropdown();
                return View("Registriraj", model);
            }

            var noviNalog = new Nalog
            {
                UserName = model.Username,
                IsKlijent = true
            };

            await userManager.CreateAsync(noviNalog, model.Password);


            Klijent klijent = new Klijent
            {
                Ime = model.Ime,
                Prezime = model.Prezime,
                GradID = model.OdabraniGradId,
                JBMG = model.JBMG,
                UserId = noviNalog.Id,
                Spol = model.Spol
            };

            context.Add(klijent);
            context.SaveChanges();




            await signInManager.SignInAsync(noviNalog, true);

            return RedirectToAction("Index","Home" );
        }

        private List<SelectListItem> GetGradoviDropdown()
        {
          return  context.Gradovi
                .OrderBy(x => x.Naziv)
                .Select(x => new SelectListItem
                {

                    Text = x.Naziv,
                    Value = x.ID.ToString()
                })
                .ToList();
        }
    }
}

Arena/Arena.Web/Views/Autentifikacija/Prijava.cshtml
@model Arena.Web.ViewModels.LoginVM
@{
    Layout = "_LayoutAutorizacija";
}
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Prijavite se kako bi nastavili</p>
            <div asp-validation-summary="ModelOnly" class="summary-errors alert alert-danger"></div>
            <form asp-action="Prijava" method="post">
                <div class="form-group">
                    <label asp-for="@Model.Username"></label>
                    <input asp-for="@Model.Username" class="form-control">
                    <span class="text-danger" asp-validation-for="@Model.Username"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Password"></label>
                    <input asp-for="@Model.Password" class="form-control">
                    <span class="text-danger" asp-validation-for="@Model.Password"></span>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input asp-for="@Model.ZapamtiPassword" type="checkbox">
                            <label asp-for="@Model.ZapamtiPassword"></label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Prijavi se</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <p class="mb-0 mt-3">
                <a asp-controller="Klijenti" asp-action="Registriraj" class="text-center">Registriraj se</a>
            </p>

        </div>
        <!-- /.login-card-body -->
    </div>
</div>