Arena/Arena.Web/Controllers/AutentifikacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Arena.EF;
using Arena.Models;
using Arena.Web.Helper;
using Arena.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Arena.Web.Controllers
{
    public class AutentifikacijaController : Controller
    {
        private MojDbContext db;
        private readonly SignInManager<Nalog> signInManager;
        private readonly UserManager<Nalog> userManager;
        private IHttpContextAccessor httpContext;

        public AutentifikacijaController(MojDbContext db, IHttpContextAccessor httpContext, SignInManager<Nalog> signInManager, UserManager<Nalog> userManager)
        {
            this.db = db;
            this.httpContext = httpContext;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public IActionResult Prijava()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public async Task<IActionResult> Prijava(LoginVM login)
        {

            if (!ModelState.IsValid)
            {
                return View(login);
            }

            //pronadjemo korisnika iz baze po korisnickom imenu
            var user = await userManager.FindByNameAsync(login.Username);
            if (user == null)
            {
                ModelState.AddModelError("","Neispravna lozinka ili kor. ime.");
                return View(login);
            }

            var signInResult = await signInManager.CheckPasswordSignInAsync(user, login.Password, false);
            if (!signInResult.Succeeded)
            {
                ModelState.AddModelError("", "Neispravna lozinka ili kor. ime.");
                return View(login);
            }

            await signInManager.SignInAsync(user, login.ZapamtiPassword);
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Odjava()
        {
            await signInManager.SignOutAsync();
            //Autentifikacija.OcistiSesiju(httpContext.HttpContext);
            return RedirectToAction("Prijava");
        }
    }
}

Arena/Arena.Web/Controllers/KorisniciController.cs
using Arena.EF;
using Arena.Models;
using Arena.Web.ViewModels;
using Arena.Web.ViewModels.Korisnici;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.Controllers
{
    public class KorisniciController : Controller
    {
        private MojDbContext db;
        private UserManager<Nalog> userManager;
        public KorisniciController(MojDbContext db, UserManager<Nalog> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index()
        {

            var model = new KorisnikPretragaVM { };

            var administratori = db.Administratori
                .Include(x => x.User)
                .Select(x => new KorisnikIndexVM
                {
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    IsAdministrator = true,
                    Grad = "",
                    ID = x.ID,
                    IsKlijent = false,
                    IsUposlenik = false,
                    JMBG = "",
                    Spol = "",
                    Username = x.User.UserName
                }).ToList();

            var klijenti = db.Klijenti
                .Include(x => x.User)
               .Select(x => new KorisnikIndexVM
               {
                   Ime = x.Ime,
                   Prezime = x.Prezime,
                   IsAdministrator = false,
                   Grad = x.Grad.Naziv,
                   ID = x.ID,
                   IsKlijent = true,
                   IsUposlenik = false,
                   JMBG = x.JBMG,
                   Spol = x.Spol,
                   Username = x.User.UserName
               }).ToList();


            var uposlenici = db.Uposlenici
                .Include(x => x.User)
              .Select(x => new KorisnikIndexVM
              {
                  Ime = x.Ime,
                  Prezime = x.Prezime,
                  IsAdministrator = false,
                  Grad = x.Grad.Naziv,
                  ID = x.ID,
                  IsKlijent = false,
                  IsUposlenik = true,
                  JMBG = "",
                  Spol = "",
                  Username = x.User.UserName
              }).ToList();



            model.RezultatPretrage = administratori;
            model.RezultatPretrage.AddRange(klijenti);
            model.RezultatPretrage.AddRange(uposlenici);

            model.RezultatPretrage = model.RezultatPretrage.OrderBy(x => x.Username).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult Pretraga(KorisnikPretragaVM model)
        {
            var loweredUsername = model.Username?.ToLower();
            var administratori = db.Administratori
                .Include(x => x.User)
                .Where(x => string.IsNullOrEmpty(loweredUsername) || x.User.UserName.ToLower().Contains(loweredUsername))
                .Select(x => new KorisnikIndexVM
                {
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    IsAdministrator = true,
                    Grad = "",
                    ID = x.ID,
                    IsKlijent = false,
                    IsUposlenik = false,
                    JMBG = "",
                    Spol = "",
                    Username = x.User.UserName
                }).ToList();

            var klijenti = db.Klijenti
                .Include(x => x.User)
                .Where(x => string.IsNullOrEmpty(loweredUsername) || x.User.UserName.ToLower().Contains(loweredUsername))
               .Select(x => new KorisnikIndexVM
               {
                   Ime = x.Ime,
                   Prezime = x.Prezime,
                   IsAdministrator = false,
                   Grad = x.Grad.Naziv,
                   ID = x.ID,
                   IsKlijent = true,
                   IsUposlenik = false,
                   JMBG = x.JBMG,
                   Spol = x.Spol,
                   Username = x.User.UserName
               }).ToList();


            var uposlenici = db.Uposlenici
                .Include(x => x.User)
                .Where(x => string.IsNullOrEmpty(loweredUsername) || x.User.UserName.ToLower().Contains(loweredUsername))
              .Select(x => new KorisnikIndexVM
              {
                  Ime = x.Ime,
                  Prezime = x.Prezime,
                  IsAdministrator = false,
                  Grad = x.Grad.Naziv,
                  ID = x.ID,
                  IsKlijent = false,
                  IsUposlenik = true,
                  JMBG = "",
                  Spol = "",
                  Username = x.User.UserName
              }).ToList();



            model.RezultatPretrage = administratori;
            model.RezultatPretrage.AddRange(klijenti);
            model.RezultatPretrage.AddRange(uposlenici);

            model.RezultatPretrage = model.RezultatPretrage.OrderBy(x => x.Username).ToList();

            return View("Index", model);
        }


        [HttpGet]
        public IActionResult DodajUposlenik()
        {
            var model = new KorisnikZaposlenikDodajVM();

            model.Gradovi = GetGradovi();
            model.Plate = GetPlate();
            model.TipoviUposlenika = GetTipoviUposlenika();


            return View("DodajUposlenik", model);
        }
        [HttpPost]
        public async Task<IActionResult> DodajUposlenik(KorisnikZaposlenikDodajVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Gradovi = GetGradovi();
                model.Plate = GetPlate();
                model.TipoviUposlenika = GetTipoviUposlenika();
                return View("DodajUposlenik", model);
            }

            var nalog = new Nalog
            {
                Id = Guid.NewGuid().ToString(),
                UserName = model.Username,
                IsUposlenik = true
            };
            await userManager.CreateAsync(nalog, model.Password);

            var noviZaposlenik = new Uposlenik
            {
                BrojTelefona = model.BrojTelefona,
                GradID = model.GradID.Value,
                Ime = model.Ime,
                Prezime = model.Prezime,
                PlataID = model.PlataID.Value,
                TipUposlenikaID = model.TipUposlenikaID.Value,
                UserId = nalog.Id
            };

            db.Uposlenici.Add(noviZaposlenik);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        private List<SelectListItem> GetTipoviUposlenika()
        {
            var items = db.TipoviUposlenika
                           .Select(x => new SelectListItem
                           {
                               Text = x.Naziv,
                               Value = x.ID.ToString()
                           }).ToList();


            items.Insert(0, new SelectListItem
            {
                Text = "--Odaberite--",
                Value = null
            });
            return items;
        }

        private List<SelectListItem> GetPlate()
        {
            var items = db.Plate
                .Select(x => new SelectListItem
                {
                    Text = x.Iznos.ToString() + "",
                    Value = x.ID.ToString()
                }).ToList();


            items.Insert(0, new SelectListItem
            {
                Text = "--Odaberite--",
                Value = null
            });
            //return items.Select(x => new SelectListItem
            //{
            //    Text = x.Iznos + "KM",
            //    Value = x.ID.ToString()
            //}).ToList();
            return items;
        }

        private List<SelectListItem> GetGradovi()
        {
            var items = db.Gradovi
                                  .Select(x => new SelectListItem
                                  {
                                      Text = x.Naziv,
                                      Value = x.ID.ToString()
                                  }).ToList();


            items.Insert(0, new SelectListItem
            {
                Text = "--Odaberite--",
                Value = null
            });
            return items;
        }
    }
}

Arena/Arena.Web/Controllers/TerminController.cs
using Arena.EF;
using Arena.Models;
using Arena.Web.ViewModels.Termini;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Arena.Web.Controllers
{
    public class TerminController : Controller
    {
        private readonly MojDbContext context;

        public TerminController(MojDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new TerminPretragaVM
            {

            };

            model.Dvorane = GetDvorane();


            model.RezultatPretrage = context.Termini
                .OrderByDescending(x=>x.DatumIVrijeme)
                 .Select(x => new TerminIndexVM
                 {
                     Cijena = x.Cijena,
                     Datum = x.DatumIVrijeme,
                     Id = x.ID,
                     NazivDvorane = x.Dvorana.Naziv
                 })
                 .ToList();
            return View(model);

        }

        [HttpPost]
        public IActionResult Pretraga(TerminPretragaVM model)
        {
            model.Dvorane = GetDvorane();
            model.RezultatPretrage = context.Termini

                .Where(x=> model.DvoranaId==null || x.DvoranaID==model.DvoranaId)
                .OrderByDescending(x=>x.DatumIVrijeme)
                 .Select(x => new TerminIndexVM
                 {
                     Cijena = x.Cijena,
                     Datum = x.DatumIVrijeme,
                     Id = x.ID,
                     NazivDvorane = x.Dvorana.Naziv
                 })
                 .ToList();
            return View("Index",model);

        }


        [HttpGet]
        public IActionResult Dodaj()
        {
            var model = new TerminDodajVM();
            model.Dvorane = GetDvorane();
            model.DatumIVrijeme = DateTime.Now;
            return View("Dodaj", model);
        }

        [HttpPost]
        public IActionResult Dodaj(TerminDodajVM model)
        {
            if(!ModelState.IsValid)
            {
                model.Dvorane = GetDvorane();
                return View("Dodaj", model);    
            }

            var noviTermin = new Termin
            {
                Cijena = model.Cijena,
                DatumIVrijeme = model.DatumIVrijeme,
                DvoranaID = model.OdabranaDvoranaId,
            };

            context.Termini.Add(noviTermin);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = new TerminEditVM();
            model.Dvorane = GetDvorane();

            var zapisIzBaze = context.Termini.Where(x => x.ID == id)
                .FirstOrDefault();

            if (zapisIzBaze == null)
                return NotFound();

            model.Id = zapisIzBaze.ID;
            model.DatumIVrijeme = zapisIzBaze.DatumIVrijeme;
            model.OdabranaDvoranaId = zapisIzBaze.DvoranaID;
            model.Cijena = zapisIzBaze.Cijena;

            return View("Edit", model);
        }


        [HttpPost]
        public IActionResult Edit(int id, TerminEditVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Dvorane = GetDvorane();
                return View("Edit", model);
            }

            var zapisIzBaze = context.Termini.Where(x => x.ID == id)
                .FirstOrDefault();

            if (zapisIzBaze == null)
                return NotFound();

            zapisIzBaze.Cijena = model.Cijena;
            zapisIzBaze.DatumIVrijeme = model.DatumIVrijeme;
            zapisIzBaze.DvoranaID = model.OdabranaDvoranaId;


            context.Termini.Update(zapisIzBaze);
            context.SaveChanges();


            return RedirectToAction("Index");
        }


        private List<SelectListItem> GetDvorane()
        {
            var items = context.Dvorana
                .OrderBy(x => x.Naziv)
                .Select(x => new SelectListItem
                {
                    Text = x.Naziv,
                    Value = x.ID.ToString()
                })
                .ToList();

            items.Insert(0, new SelectListItem
            {
                Value = null,
                Text = "Odaberite dvoranu"
            });

            return items;
        }
    }
}

Arena/Arena.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

            </ul>

        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-controller="Home" class="brand-link">
                <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Arena</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a asp-controller="Home" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-user"></i>
                                <p>
                                    Početna stranica
                                </p>
                            </a>
                        </li>


                        <li class="nav-item has-treeview ">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-briefcase"></i>
                                <p>
                                    Poslovanje
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview" >
                                <li class="nav-item">
                                    <a asp-controller="Termin" asp-action="Index"  class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Termini</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Rezervacije" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Rezervacije</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                       
                        <li class="nav-item">
                            <a asp-controller="Korisnici" asp-action="Index" class="nav-link">
                                <i class="nav-icon far fa-user"></i>
                                <p>
                                    Korisnici
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-controller="Autentifikacija" asp-action="Odjava" class="nav-link">
                                <i class="nav-icon fa fa-close"></i>
                                <p>
                                    Odjava
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">@ViewData["Title"]</h1>
                        </div><!-- /.col -->

                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.0.5
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="js/demo.js"></script>
</body>
</html>






@*<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Arena.Web</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cerulean.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <title>ArenaGroup</title>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        </environment>
        <link rel="stylesheet" href="~/css/site.css" />



    </head>
    <body>


        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Arena.Web</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>




                        </ul>

                    </div>
                </div>
            </nav>
        </header>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

            </ul>




        </div>*@






@*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Arena.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

@*<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>*@



@RenderSection("Scripts", required: false)

@*</body>
    </html>*@

Arena/Arena.Web/Views/Shared/_LayoutAutorizacija.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">

    @RenderBody()
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>

</body>
</html>